### ISSUE TITLE
NBfetch should pull public HS resources without authentication

### ISSUE THREAD

**Issue by devincowan** [hydroshare/nbfetch#12]
[Before login](https://github.com/hydroshare/nbfetch/blob/c742635ae32c4fa17b0885114501325e6a9d93b7/nbfetch/handlers.py#L375) check if private or public
If a user isn’t required, we need to allow the functionality for public resources to work without a login
We think we “accidentally” prevented this when we refactored the nbfetch work
If private resources, we need to pop up dialog and give the ability to cache credentials in the JH instance
OIDC handshake w Keycloak
Use HS Login dialog to save credentials inside environment

**Comment by devincowan** [comment]
Testing with a local build of nbfetch at this commit: https://github.com/hydroshare/nbfetch/commit/c742635ae32c4fa17b0885114501325e6a9d93b7

It looks like nbfetch is able to pull public Hydroshare resouces without authentication
@Castronova do you know what version of this nbfetch was installed for our CIROH collaborators?

**Comment by Castronova** [comment]
That is a very good question. I believe that we configured this on October 6, 2023 from the master branch: `git+https://github.com/hydroshare/nbfetch.git@master`. We haven't had any code merged into `master` since then so perhaps this isn't the issue that they're encountering.

**Comment by devincowan** [comment]
I was incorrect [above](https://github.com/hydroshare/nbfetch/issues/12#issuecomment-1981870890) -- I had cached credentials that were making it look like I could pull public HS resources without authentication.
